### ISSUE TITLE
multi RPC client handler

### ISSUE THREAD

**Issue by SirTLB** [White-Whale-Defi-Platform/white-whale-bots#28]
When people are reliant on the availability of public nodes, they get usually blocked out a lot by specific rpc clients. We'd like to be able to provide a list of known public rpc's, of which the bot selects one. When the bot errors on querying the node because of rate limits, we switch the client to a different rpc endpoint and reinitialise the clients.

**Comment by nick134-bit** [comment]
I'll add this to the next update
