### ISSUE TITLE
Add dynamic skipBidRate

### ISSUE THREAD

**Issue by LittleLionMan** [White-Whale-Defi-Platform/white-whale-bots#31]
In my desperate quest to work on one of my ideas I channeled the coding skills of a 5y old and added the following on line 98 in ../src/types/arbitrage/skipLoop.ts
if (arbTrade.profit > 10000000) {
			this.botConfig.skipBidRate = 0.51;
}
if (arbTrade.profit > 100000000) {
	this.botConfig.skipBidRate = 0.81;
}
This resulted in some unprofitable arbs. This came with no surprise, because arbTrade.profit obviously doesn't calculate in the new skipBidRate like this.
However, many examples indicated that changes in the skipBidRate did not depend on the profit, but on the amount of the flash loan taken. Two examples:
https://www.mintscan.io/juno/txs/945A11F0698FFE3DDF1DB19A55313862C89570D25BC63D053915AC9444782FE2
https://www.mintscan.io/juno/txs/83E183BF08BB10C9000D008EE78F97B608AD0E8A5960A42A4129C3F6864CB6F5

Once in a while this assessment gets contradicted though.
https://www.mintscan.io/juno/txs/329EB8791B5C1544BBBD365AF9C94CC93067F9769195E9CFD35BA6344037EC09
https://www.mintscan.io/juno/txs/D189034E1BAECDCAA6727B76BF52B37C9F40A862DBB503D35496C9C6703D8D88

**Comment by SirTLB** [comment]
@LittleLionMan yeah so what happens when you alter the class (the loop) in runtime, the loop works async so the next few steps are already lined up and will not use the new skip-bit-rate. We'd have to provide a dynamic threshold on the initialisation of the loop, like saying we assign a skip-bid-rate to a profit threshold? So we could provide something like 
[{5, .1}, {10, .2}, {50, .5}]? Then we have to simply assign a skip bid rate based on the expected profit. Would that make sense?

**Comment by LittleLionMan** [comment]
absolutely! I was just too lazy to figure out the correct step in the code to manipulate the bid rate. However, I'm still confused why the bot bid >0,81 on very small profits. The only ostentatious part I could figure out was the amount of the flash loan, but it might be coincidence

**Comment by SirTLB** [comment]
@LittleLionMan we can also consider using a more absolute value for our profit threshold. So we just say <1juno bid X, <10 juno bid Y and so on. What has your preference?

**Comment by LittleLionMan** [comment]
I think both solutions have advantages (the second is more straightforward), but I will try the first, because it gives more freedom to the user. Introduce a new variable in the .env and iterate through the array with the expected profit. Sadly I'm very busy these days and hadn't any time to play with it.

**Comment by SirTLB** [comment]
@LittleLionMan I think we should do it like this: 

- set a maximum skip bid rate
- set a minimum skip bid rate
- set an increment of the skip bid rate
loop through the above in increasing fashion
