### ISSUE TITLE
Remove the need for manually entered pool input/output fees

### ISSUE THREAD

**Issue by carlthelooper** [White-Whale-Defi-Platform/white-whale-bots#33]
---
## Improvement description

It would be helpful to have a way to get the input and output fees without having to manually enter them for every pool defined within a config.  

Some options on how this could be accomplished:
- Create centralized location with all input and output fees for DEXes on a give chain. 
- Add some automated process integrated into the bot that queries the DEXes/pools to determine the proper fees. 

---

### Additional context

Example of current config where `inputfee` and `outputfee` must be definied.
```
POOLS = '
 {"pool": "juno1sg6chmktuhyj4lsrxrrdflem7gsnk4ejv6zkcc4d3vcqulzp55wsf4l4gl","inputfee": 0.3, "outputfee": 0},
 {"pool": "juno124d0zymrkdxv72ccyuqrquur8dkesmxmx2unfn7dej95yqx5yn8s70x3yj","inputfee": 0.4,"outputfee": 0}'
```

**Comment by SirTLB** [comment]
The problem with is is that it's not certain fees can be determined by a query. E.g. HOPERS dex and a lot of junoswap pools do not expose the fees via query.

**Comment by silvermind** [comment]
@SirTLB what's the plan on this? Atm the Sample POOLS Var in e.g. the terra.env does not contain all Pools available. And it's quiet a work to update them manually. Would it make sense to add a script which can update these samples with all available pools?

But not sure whats the best source of the actual pools atm.. 
E.g. when quering the WW Dex Pool Factory on Terra, https://terrasco.pe/mainnet/address/terra1f4cr4sr5eulp3f2us8unu6qv8a5rhjltqsg7ujjx6f2mrlqh923sljwhn3 only 10 pools are returned. 
E.g. this one Luna/LunaX is missing https://terrasco.pe/mainnet/address/terra1qzux5j9he9nv95kq3unkuzy0hddf080um2t243raatg3f6requwsaahpqp

---
A sample using the tfm endpoint which returns all 14 WW Pools on Terra.
https://prod-juno.analytics.tfm.com/graphql
```
{
  pair(chain: "terra2", limit: 10000, market: "Whitewhale") {
    content {
    token0Addr,
    token1Addr,
    swapFee,
    contractAddr,
      createdAt,
    market,
     stable,
      highestLiquidity
    }
  }
}

```
---

## Terra Mainnet Sources
White Whale Pool Factory factory: https://terrasco.pe/mainnet/address/terra1f4cr4sr5eulp3f2us8unu6qv8a5rhjltqsg7ujjx6f2mrlqh923sljwhn3
White Whale Pool Router router: https://terrasco.pe/mainnet/address/terra1p37jrwlaqpklzlu4rwjyjrmzuezdgk3pyuyk2zclc4rda6awkm3qnj6f0a

astro factory: https://terrasco.pe/mainnet/address/terra14x9fr055x5hvr48hzy2t4q7kvjvfttsvxusa4xsdcy702mnzsvuqprer8r
astroport router: https://terrasco.pe/mainnet/address/terra1j8hayvehh3yy02c2vtw5fdhz9f4drhtee8p5n5rguvg3nyd6m83qd2y90a

terra swap factory: https://terrasco.pe/mainnet/address/terra1466nf3zuxpya8q9emxukd7vftaf6h4psr0a07srl5zw74zh84yjqxl5qul
terra swap router: https://terrasco.pe/mainnet/address/terra13ehuhysn5mqjeaheeuew2gjs785f6k7jm8vfsqg3jhtpkwppcmzqcu7chk

phoenix swap factory factory: https://terrasco.pe/mainnet/address/terra1pewdsxywmwurekjwrgvjvxvv0dv2pf8xtdl9ykfce2z0q3gf0k3qr8nezy
phoenix swap router: https://terrasco.pe/mainnet/address/terra1r634fv9kj8s6vjgnrwdha35cwhz6jcpz0h0trhc4yehllvtzzxuq5slv0g
