### ISSUE TITLE
Update Bot to use latest skipjs

### ISSUE THREAD

**Issue by silvermind** [White-Whale-Defi-Platform/white-whale-bots#39]
## Steps to Reproduce

- I accidentally used yarn to get the latest packages so i ened up to all latest versions. (NOTE: with npm install it worked as its using the package-lock.json ) 

### Additional context

This commit in skipjs break the current implementation of the skipLoop at:
https://github.com/White-Whale-Defi-Platform/white-whale-bots/blob/main/src/types/arbitrage/skipLoop.ts#L137

https://github.com/skip-mev/skipjs/commit/73ae64202166b7077f128dbe529ffac9210b2c0d#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

- https://github.com/skip-mev/skipjs

tried this implementation but the mthod to get the key getAccountsWithPrivkeys is private.

```
// broken
const privKey = (await this.skipSigner.getAccountsWithPrivkeys())[0].privkey

const txToArbRawString = Buffer.from(txToArbRaw).toString('base64')
const txRawString = Buffer.from(txRaw).toString('base64')
const signed = await this.skipClient.signBundle([txToArbRawString, txRawString], privKey);


```

**Comment by SirTLB** [comment]
We are aware, we will have to change the skipsigner to a different method in order to use latest version of skip, lets see if we can solve this soon

**Comment by SirTLB** [comment]
will be fixed when we implement POB
