### ISSUE TITLE
tendermint-rpc Bad status on response: 500

### ISSUE THREAD

**Issue by Roalkege** [White-Whale-Defi-Platform/white-whale-bots#48]
If you want to report a security issue, please follow our security policy: `https://github.com/White-Whale-Defi-Platform/migaloo-core/blob/main/SECURITY.md`

---
## Steps to Reproduce

1. See Log 
2. `npm start` and wait around 350-600 Blocks 
3. tendermint-rpc Bad status response: 500 

**Expected results:** 
App waits x seconds and tries again.

**Actual results:** 
App is crashing. (Log)

---

### Additional context
Add any other context about the problem here, code snippets, json responses and so on.

</details>

<details>
  <summary>Logs</summary>

```
/home/dietpi/white-whale-bots/node_modules/@cosmjs/tendermint-rpc/build/rpcclients/http.js:10
throw new Error(`Bad status on response: ${res.status}`);   
^

Error: Bad status on response: 500
at filterBadStatus (/home/dietpi/white-whale-bots/node_modules/@cosmjs/tendermint-rpc/build/rpcclients/http.js:10:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.6.0
```

**Comment by zJuuu** [comment]
This is most likely a error from the rpc and no issue with the bot. What rpc do you use?

**Comment by Roalkege** [comment]
I use `https://juno-rpc.reece.sh`. You are right I think the bug label is not the correct, it should be improvement. 

I think its a unplanned behavior when the bots crashes with a 500 response. Why not just wait 30 secs and try it again.

**Comment by SirTLB** [comment]
@zJuuu @kaimen-sano I think we should just catch this one, wait a bit and retry. Maybe we can also use something like the rpc switcher we want in #28
