### ISSUE TITLE
Fix Link to CONTRIBUTING.md File in PR Template

### ISSUE THREAD

**Issue by silvermind** [White-Whale-Defi-Platform/white-whale-bots#81]
When creating a new MergeRequest in this Repo, a Checklist is shown, but the link to the CONTRIBUTING.md file is broken as the file now is in a renamed repo under /docs.

```
## Checklist:

- [x ] I have read [Migaloo's contribution guidelines](**https://github.com/White-Whale-Defi-Platform/migaloo-bots/blob/main/CONTRIBUTING.md**).
```

✅ https://github.com/White-Whale-Defi-Platform/white-whale-bots/blob/main/docs/CONTRIBUTING.md

**Comment by SirTLB** [comment]
fixed with a direct commit into release branch. Thanks for pointing it out!
